import {
  HEARINGROLE_INVITEE,
  HEARINGROLE_RESPONDER,
  HEARINGSTATUS_ACTIVE,
  HEARINGSTATUS_AWAITING_CONCLUSION,
  HEARINGSTATUS_AWAITING_STARTDATE,
  HEARINGSTATUS_CONCLUDED,
} from "./constants/api";
import { FILTER_PROPERTIES } from "./constants/filterProperties";
import { ACTIVE_HEARINGS_PAGE, ARCHIVED_HEARINGS_PAGE, MY_HEARINGS_PAGE } from "./constants/pages";
import { PaginatedItems } from "./constants/paginatedItems";
import { PaginationFilters } from "./paginationFilters";

export const defaultPageFilters = {
  [ACTIVE_HEARINGS_PAGE]: [
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.HEARING_STATUS](HEARINGSTATUS_ACTIVE),
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.HEARING_STATUS](HEARINGSTATUS_AWAITING_STARTDATE),
  ],
  [MY_HEARINGS_PAGE]: [
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.USER_HEARING_ROLE](HEARINGROLE_INVITEE),
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.USER_HEARING_ROLE](HEARINGROLE_RESPONDER),
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.COMPANY_HEARING_ROLE](HEARINGROLE_INVITEE),
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.COMPANY_HEARING_ROLE](HEARINGROLE_RESPONDER),
  ],
  [ARCHIVED_HEARINGS_PAGE]: [
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.HEARING_STATUS](HEARINGSTATUS_AWAITING_CONCLUSION),
    PaginationFilters[PaginatedItems.HEARINGS][FILTER_PROPERTIES.HEARING_STATUS](HEARINGSTATUS_CONCLUDED),
  ],
};
