import { TranslationContextInterface } from "../contexts/Translation";

const da: TranslationContextInterface = {
  // ---------- Front page ----------
  frontpage: {
    metaTitle: "Høringsportalen",
    metaDescription: "Find og læs aktive og arkiverede høringer fra Ballerup Kommune, og giv din mening til kende",
    title: "Ballerup Kommunes Digitale Høringsportal",
    text:
      "Via denne portal, kan du gøre opmærksom på dine synspunkter, vedrørende en igangværende høring. En høring kan omhandle ændringer i vores serviceydelser til fx børn, ældre eller det kan være i relation til dit lokalområde.",
    imageAlt: "Ballerup Kommune Logo",
    card1Title: "Aktive høringer",
    card1Text: "Læs og besvar aktive høringer",
    card1AriaLabel: "Læs og svar på de aktuelle høringer",
    card2Title: "Mine høringer",
    card2Text: "Se dine tidligere høringssvar",
    card2AriaLabel: "Læs og svar på høringer du er en del af",
    card3Title: "Arkiverede høringer",
    card3Text: "Oversigt over afsluttede høringer",
    card3AriaLabel: "Læs de arkiverede høringer",
  },
  global: {
    loginRequiredTitle: "Siden kræver login",
    loginRequiredText: "Denne her side kræver at du er logget ind. Klik på knappen for at logge ind.",
    loginRequiredButton: "Log ind",
    fileUploadErrorTitle: "Fejl ved upload",
    fileUploadErrorText: "Der opstod en fejl ved upload af nedestående bilag. De var enten for store eller helt tomme",
    fileUploadErrorButton: "Forstået",
    commentCreatedTitle: "Høringssvar modtaget!",
    commentCreatedText: "Dit høringssvar er modtaget, og vil blive behandlet.",
    commentCreatedButton: "Se dit høringssvar",
    commentErrorTitle: "Ukendt fejl!",
    commentErrorText:
      "Der er desværre sket en fejl. Fejlen kan være du ikke er logget ind. Tjek gerne dette, og forsøg at log ind.",
    commentUploadFilesErrorTitle: "Fejl ved upload af bilag",
    commentUploadFilesErrorText: "Nogle af bilagene kunne ikke uploades. Slet dem eller prøv igen",
    commentErrorButton: "Luk, og forsøg igen",
    commentDeletedTitle: "Høringssvar slettet!",
    commentDeletedText: "Dit høringssvar er slettet, og vil ikke længere blive behandlet.",
    commentDeletedButton: "Opdater siden",
    commentUpdatedTitle: "Høringssvar modtaget!",
    commentUpdatedText: "Dit høringssvar er opdateret, og vil blive behandlet.",
    commentUpdatedButton: "Se dit høringssvar",
    pageLoadingText: "Vi arbejder på at hente siden til dig...",
    awaitingStartdateText: "Afventer startdato",
    activeStatusText: "I gang",
    awaitingConclusionStatusText: "Afventer konklusion",
    concludedStatusText: "Konkluderet",
  },
  accessdenied: {
    metaTitle: "Høringsportalen | Adgang nægtet",
    metaDescription: "Nægtet adgang til høring",
    title: "Der er sket en fejl",
    text:
      "Det kan være siden du prøver at tilgå kræver, at du er logget ind eller, at der er sket en anden fejl. Prøv at logge ind med login knappen, i øverste højre hjørne, og gentag handlingen. Oplever du fortsat problemer, kontakt da høringsejer. Du finder kontaktinformation på høringsejer nederst på hørings siden.",
    buttonText: "Login",
    imageAlt: "Ballerup Kommune Logo",
  },
  activeHearings: {
    metaTitle: "Høringsportalen | Aktive Høringer",
    metaDescription: "Oversigt over aktive høringer fra Ballerup Kommune. Giv din mening til kende",
    title: "Aktive høringer",
    filter: "Filtrering",
    filterCheckboxLabel: "Fagområde",
    filterRadioButtonLabel: "Høringer",
    filterSubmitText: "Anvend Filter",
    filterTitle: "Filtrering",
    filterCloseButtonLabel: "Luk filtrering",
    searchPlaceholder: "Søg",
    hearingLinkText: "Læs og besvar høring",
    hearingDeadlineTitle: "Svarfrist",
    noHearingsTitle: "Ingen aktive høringer",
    noHearingsText:
      "Der er ikke nogle igangværende høringer.\r\n\r\n Er du inviteret til en høring som du ikke kan se her, så prøv at logge ind.",
    searchLabel: "Søg efter en aktiv høring:",
  },
  archivedHearings: {
    metaTitle: "Høringsportalen | Arkiverede Høringer",
    metaDescription: "Oversigt over arkiverede høringer fra Ballerup Kommune. Giv din mening til kende",
    title: "Arkiverede høringer",
    filter: "Filtrering",
    filterCheckboxLabel: "Fagområde",
    filterRadioButtonLabel: "Høringer",
    filterSubmitText: "Anvend Filter",
    filterTitle: "Filtrering",
    filterCloseButtonLabel: "Luk filtrering",
    searchPlaceholder: "Søg",
    hearingLinkText: "Læs høring",
    hearingDeadlineTitle: "Svarfrist",
    noHearingsTitle: "Ingen arkiverede høringer",
    noHearingsText:
      "Det ser ikke ud som om der er nogle arkiverede høringer.\r\n\r\n Dette kan skyldes du ikke er logget ind, eller at der endnu ikke er nogle arkiverede høringer.",
    searchLabel: "Søg efter en arkiveret høring:",
  },
  myHearings: {
    metaTitle: "Høringsportalen | Mine Høringer",
    metaDescription:
      "Oversigt over høringer, du har besvaret eller er inviteret til, fra Ballerup Kommune. Giv din mening til kende",
    title: "Mine høringer",
    filter: "Filtrering",
    filterCheckboxLabel: "Fagområde",
    filterRadioButtonLabel: "Høringer",
    filterSubmitText: "Anvend Filter",
    filterTitle: "Filtrering",
    filterCloseButtonLabel: "Luk filtrering",
    searchPlaceholder: "Søg",
    hearingLinkText: "Læs og besvar høring",
    hearingDeadlineTitle: "Svarfrist",
    noHearingsTitle: "Du har ingen tilknyttede høringer",
    noHearingsText:
      "Der er ikke nogle tilnyttede høringer at vise.\r\n\r\n Det kan skyldes at du ikke er logget ind, at du ikke er inviteret til en høring eller at du endnu ikke har besvaret en høring.",
    searchLabel: "Søg efter en af dine høringer:",
    readCommentsLabel: "Se besvarelser",
  },
  hearing: {
    metaTitle: "Høringsportalen | ##hearing##",
    metaDescription: "Høring omhandlede ##hearing## i Ballerup Kommune. Giv din mening til kende",
    startDateTitle: "Startdato",
    endDateTitle: "Svarfrist",
    statusTitle: "Status",
    summary: "Resumé",
    bodyInformationText: "Høringstekst",
    bodyInformationFiles: "Bilag",
    conclusionText: "Konklusion",
    generalInformation: "Generel Information",
    contactInformation: "Kontaktinformation",
    seeHearingAnswersButton: "Se Høringssvar",
    answerHearingButton: "Afgiv Høringssvar",
    answerHearingAfterLoginButton: "Log ind og afgiv høringssvar",
    subjectArea: "Fagområde:",
    status: "Status:",
    caseNumber: "Sagsnummer:",
    department: "Afdelingsnavn",
    contactPerson: "Kontaktperson",
    email: "E-mail",
    phoneNumber: "Telefon",
    noAccessTitle: "Ups, der er sket en fejl, prøv igen senere.",
    noAccessText:
      "Hvis problemet fortsætter, kan du kontakte os på ballerup-dk@balk.dk eller du kan kontakte høringsejer direkte, se kontaktdetaljer under den specifikke høring.",
  },
  comments: {
    metaTitle: "Høringsportalen | ##hearing##",
    metaDescription: "Læs kommentarer til høring omhandlede ##hearing## i Ballerup Kommune. Giv din mening til kende",
    startDateTitle: "Startdato",
    endDateTitle: "Svarfrist",
    statusTitle: "Status",
    summary: "Resumé",
    hearingAnswer: "Høringssvar",
    commentNumber: "Svarnummer:",
    answerHearingButton: "Afgiv høringssvar",
    answerHearingAfterLoginButton: "Log ind og afgiv høringssvar",
    readHearingButton: "Læs høring",
    hiddenHearingAnswers: "Høringssvar skrevet af andre er skjulte, men vil alle blive taget i betragtning",
    noHearingAnswers: "Der er endnu ikke nogle høringssvar. Vær den første til at give din mening til kende",
    noAccessTitle: "Ups, der er sket en fejl, prøv igen senere.",
    noAccessText:
      "Hvis problemet fortsætter, kan du kontakte os på ballerup-dk@balk.dk eller du kan kontakte høringsejer direkte, se kontaktdetaljer under den specifikke høring.",
    onBehalfOfLabel: "På vegne af:",
    deleteCommentTooltip: "Slet høringssvar",
    editCommentTooltip: "Rediger høringssvar",
  },
  answer: {
    metaTitle: "Høringsportalen | ##hearing##",
    metaDescription: "Giv din mening til kende om høringen omhandlede ##hearing## i Ballerup Kommune",
    startDateTitle: "Startdato",
    endDateTitle: "Svarfrist",
    statusTitle: "Status",
    summary: "Resumé",
    hearingAnswer: "Høringssvar",
    postHearingAnswerButton: "Indsend høringssvar",
    answerOnBehalfOf: "Svar på vegne af andre",
    onBehalfOfPlaceholder: "Svar på vegne af andre...",
    writeHearingAnswerPlaceholder: "Skriv høringssvar...",
    attachFiles: "Vedhæft bilag",
    buttonFileUpload: "Klik for at uploade et bilag",
    dropFileUpload: "Klik eller træk for at uploade bilag",
    dropFileUploadDrop: "Slip bilag for at uploade",
    termsAndConditionsLabel: "Betingelser",
    termsAndConditions: "Klik for at læse, og acceptere betingelserne",
    termsAndConditionsTitle: "Afgivelse af svar",
    termsAndConditionsAccept: "Jeg accepterer betingelserne",
    noAccessTitle: "Ups, der er sket en fejl, prøv igen senere",
    noAccessText:
      "Hvis problemet fortsætter, kan du kontakte os på ballerup-dk@balk.dk eller du kan kontakte høringsejer direkte, se kontaktdetaljer under den specifikke høring.",
    onBehalfOfLabel: "På vegne af:",
    hearingAnswerLabel: "Høringssvar:",
    hearingAnswerHelperText:
      "Høringssvaret skal så vidt muligt indsættes i høringssvar feltet, og hvis dit høringssvar fremgår af dit bilag, bedes du kopiere det fra bilaget og ind i høringssvar feltet. For at hjælpe behandlingen af dit svar, bedes du henvise til dine bilag i høringsteksten med bilagets navn.",
    maximumFileSize: "Maksimal bilagstørrelse",
  },
  termsAndConditions: {
    metaTitle: "Høringsportalen | Databeskyttelse",
    metaDescription: "Databeskyttelse i forbindelse med brug af høringsportalen",
    title: "Databeskyttelse",
  },
};

export { da };
