const ENV_VARIABLE = {
  MAIN_LOGO: "MAIN_LOGO",
  FALLBACKIMAGE: "FALLBACKIMAGE",
  HEADER_LOGO: "HEADER_LOGO",
  FOOTER_LOGO: "FOOTER_LOGO",
  RENDER_NARROW_HEARING_IMAGE: "RENDER_NARROW_HEARING_IMAGE",
  THEME: "THEME",
  X_API_HEADER: "X_API_HEADER",
  API_URL: "API_URL",
  HIDE_RESPONDER_INFO: "HIDE_RESPONDER_INFO",
  SHOW_CASE_NUMBER: "SHOW_CASE_NUMBER",
  RESPONSE_LIMIT: "RESPONSE_LIMIT",
  HEARINGOWNER_RESPONSE_LIMIT: "HEARINGOWNER_RESPONSE_LIMIT",
  PREFETCH_TIMEOUT: "PREFETCH_TIMEOUT",
  PAGE_SIZE_HEARINGS: "PAGE_SIZE_HEARINGS",
  PAGE_SIZE_COMMENTS: "PAGE_SIZE_COMMENTS",
  PAGINATE_HEARINGS: "PAGINATE_HEARINGS",
  PAGINATE_COMMENTS: "PAGINATE_COMMENTS",
};

export { ENV_VARIABLE };
